### ISSUE TITLE
Venta en Efectivo como Herencia

### ISSUE THREAD

**Issue by JulianEzequiel** [leobz/DDS.Macowins#7]
Según el enunciado, hay dos tipos de Ventas: en Efectivo y con Tarjeta de Crédito. En qué se diferencian las dos? En que la venta con tarjeta calcula de forma distinta el importe a pagar.

Ahora bien, que comportamiento tiene la Venta en Efectivo que difiere de la Venta? Por lo que puedo ver en tu código, no hay un comportamiento que justifique esta herencia. Podemos considerar que la Venta en Efectivo es la venta normal, y que la Venta con Tarjeta si tiene sentido que sea una clase aparte porque si tiene un comportamiento distinto.

En el contexto de este ejercicio, la Venta en Efectivo como clase aparte no aporta ninguna solución al dominio, y tal vez hasta lo hace un poco más complejo. Por eso, no debería usarse esta herencia, y la Venta en Efectivo debería ser solo la Venta.

**Comment by leobz** [comment]
Tenia esa duda!

**Comment by leobz** [comment]
Hola juli! La razón por la que no puse que Venta con Tarjeta herede de Venta en Efectivo es que no me parecía tan racional expresivamente.
Por eso, para que Venta en Efectivo tenga un comportamiento y no solo herede y no haga nada, ahora le agregué el método abstracto recargo(), que es manejado de manera diferente para Venta en Efectivo y para Venta con Tarjeta, siendo de cero para la primera y aplicando las condiciones del cliente para la segunda, de esta manera si en un futuro agregase otro tipo de venta, solo tendría que modificar el recargo.
